# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 				echesters
description: 		> # this means to ignore newlines until "baseurl:"
  Elizabeth Chesters, a user experience consultant by day and a developer 
  by night. Here you can check out her blog posts from UX to teaching, 
  and her portfolio in UX and photography. If that doesn't tickle your fancy, 
  check out her Twitter for cooking.
url: 				"/echesters.github.io" # the base hostname & protocol for your site
twitter_username: 	echesters
github_username:  	echesters
# permalink:			/:title
# baseurl:			"echesters.github.io"

exclude: 			[vendor]

# Build settings
markdown: kramdown

gem: jekyll-paginate
paginate: 9